### ISSUE TITLE
matrix/element installation - failure

### ISSUE THREAD

**Issue by florianwilde** [bashclub/zamba-lxc-toolbox#102]
Bei der Installation von Matrix aus der Zamba-LXC-Toolbox kommen einige Fehlermeldungen, weswegen die Installation fehlschlägt und nicht erfolgreich beendet wird.

Siehe hier:

`Created symlink /etc/systemd/system/multi-user.target.wants/matrix-synapse.service → /lib/systemd/system/matrix-synapse.service.
Job for matrix-synapse.service failed because the control process exited with error code.
See "systemctl status matrix-synapse.service" and "journalctl -xe" for details.`

Und noch einige andere:

`--2024-01-08 13:28:45--  https://packages.riot.im/element-release-key.asc
Auflösen des Hostnamens packages.riot.im (packages.riot.im)… 104.26.4.138, 172.67.70.226, 104.26.5.138, ...
Verbindungsaufbau zu packages.riot.im (packages.riot.im)|104.26.4.138|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 301 Moved Permanently
Platz: https://packages.element.io/element-release-key.asc [folgend]
--2024-01-08 13:28:45--  https://packages.element.io/element-release-key.asc
Auflösen des Hostnamens packages.element.io (packages.element.io)… 172.67.12.112, 104.22.48.198, 104.22.49.198, ...
Verbindungsaufbau zu packages.element.io (packages.element.io)|172.67.12.112|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK`

Ebenso hier:

`--2024-01-08 13:28:45--  https://github.com/vector-im/element-web/releases/download//element-.tar.gz
Auflösen des Hostnamens github.com (github.com)… 140.82.121.3
Verbindungsaufbau zu github.com (github.com)|140.82.121.3|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 301 Moved Permanently
Platz: https://github.com/element-hq/element-web/releases/download/element-.tar.gz [folgend]
--2024-01-08 13:28:45--  https://github.com/element-hq/element-web/releases/download/element-.tar.gz
Wiederverwendung der bestehenden Verbindung zu github.com:443.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 404 Not Found
2024-01-08 13:28:46 FEHLER 404: Not Found.`

`--2024-01-08 13:28:46--  https://github.com/vector-im/element-web/releases/download//element-.tar.gz.asc
Auflösen des Hostnamens github.com (github.com)… 140.82.121.3
Verbindungsaufbau zu github.com (github.com)|140.82.121.3|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 301 Moved Permanently
Platz: https://github.com/element-hq/element-web/releases/download/element-.tar.gz.asc [folgend]
--2024-01-08 13:28:46--  https://github.com/element-hq/element-web/releases/download/element-.tar.gz.asc
Wiederverwendung der bestehenden Verbindung zu github.com:443.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 404 Not Found
2024-01-08 13:28:46 FEHLER 404: Not Found.`

`gpg: verify signatures failed: Unknown system error`

`gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
mv: der Aufruf von stat für 'element-' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
chown: Zugriff auf '/var/www/element-web' nicht möglich: Datei oder Verzeichnis nicht gefunden
cp: der Aufruf von stat für '/var/www/element-web/config.sample.json' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
sed: /var/www/element-web/config.json kann nicht gelesen werden: Datei oder Verzeichnis nicht gefunden
sed: /var/www/element-web/config.json kann nicht gelesen werden: Datei oder Verzeichnis nicht gefunden
CREATE ROLE`

**Comment by thorstenspille** [comment]
Hi Florian,
Das sieht ganz danach aus, als ob im Container entweder DNS nicht richtig konfiguriert ist oder vom DNS Server Anfragen geblockt werden.
Läuft im Netz ein pihole oder ein DNS Resolver mit Blocklisten?
Wie sieht die zamba conf aus?

**Comment by florianwilde** [comment]
Hi Thorsten,
von intern nach extern wird Testzwecken rein gar nichts geblockt.
Und als DNS wird 8.8.8.8 also der Google DNS verwendet.
Sieht also ganz kurios aus. 
In der zamba conf sowie in der resolv conf ist auch der 8.8.8.8 als DNS eingetragen.

`root@srv-rz3-matrix:~# nslookup
> server
Default server: 8.8.8.8
Address: 8.8.8.8#53
> github.com
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
Name:   github.com
Address: 140.82.121.4
`

**Comment by thorstenspille** [comment]
Element Repo wurde umgezogen, ist nun im dev gefixt, release kommt bald.
