### ISSUE TITLE
share access denied after new installation

### ISSUE THREAD

**Issue by X-Renegade-X** [bashclub/zamba-lxc-toolbox#104]
Hi,
i have a fresh installation of zamba-LXC-toolbox as an ad-member.
First the server is not shown automatically in windows 11.  Second if i get it with\\SERVERNAME\ it will be shown, but access denied and owner is not changeable. In shell the groups and users from domain are shown.

If i log in with the User Administrator, i can change rights and it works, but if i set the Admin group as owner just the Admin can change rights an no other user from th group.

**Comment by thorstenspille** [comment]
Currently please use the dev branch, we are currently testing the installers and release soon.
