### ISSUE TITLE
GPG-Error / Unifi

### ISSUE THREAD

**Issue by floppy007** [bashclub/zamba-lxc-toolbox#107]
I get a GPG error when installing the Unificontroller resp. the Mongo DB

GPG-Fehler: http://repo.mongodb.org/apt/debian stretch/mongodb-org/3.6

![Screenshot 2024-03-27 221739](https://github.com/bashclub/zamba-lxc-toolbox/assets/47177775/37a67ee7-bade-44f0-a0cf-a2d2cbeddfe8)

**Comment by thorstenspille** [comment]
Please use the dev branch, its updated there.
`git clone -b dev https://github.com/bashclub/zamba-lxc-toolbox`

**Comment by thorstenspille** [comment]
Unifi Controller on Debian 12 with default-jre and mongodb-org 7 now in dev, will be released soon.
