### ISSUE TITLE
Mailpiler not working

### ISSUE THREAD

**Issue by HeikoBei** [bashclub/zamba-lxc-toolbox#110]
Hi there,
I tried to install mailpiler as shown in the video and on aow.de, but there's a authorization issue with bitbucket.org:

--2024-05-28 18:00:05--  https://bitbucket.org/jsuto/piler/downloads/piler-1.3.12.tar.gz
Auflösen des Hostnamens bitbucket.org (bitbucket.org)… 104.192.141.1, 2406:da00:ff00::22c5:2ef4, 2406:da00:ff00::22cd:e0db, ...
Verbindungsaufbau zu bitbucket.org (bitbucket.org)|104.192.141.1|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 401 Unauthorized

Authentifizierung mit Benutzername/Passwort fehlgeschlagen.
tar (child): piler-1.3.12.tar.gz: Funktion open fehlgeschlagen: Datei oder Verzeichnis nicht gefunden
tar (child): Error is not recoverable: exiting now

After that lot's of follow up errors show up.

Is this temporary does this need to be fixed.
Thanks
Heiko

**Comment by cpzengel** [comment]
Please use -b dev

**Comment by thorstenspille** [comment]
https://aow.de/books/lxc-toolbox-fur-proxmox/page/piler-mailarchiv-145

`git clone -b dev https://github.com/bashclub/zamba-lxc-toolbox`
