### ISSUE TITLE
Update locale non interactive

### ISSUE THREAD

**Issue by LAWA-IT-Service** [bashclub/zamba-lxc-toolbox#22]
Changing the locale via script is possible in the following way 

`sed -i "s/^#.$LXC_LOCALE/$LXC_LOCALE/" /etc/locale.gen`
`locale-gen $LXC_LOCALE`
`echo   LANG=$LXC_LOCALE > /etc/default/locale`
`echo   LANGUAGE=$LXC_LOCALE >> /etc/default/locale`
`export LANG=$LXC_LOCALE`

Hint change zamba.conf to
`LXC_LOCALE=de_DE.UTF-8`

**Comment by thorstenspille** [comment]
Hi @LAWA-IT-Service,
thanks for your Ticket.
In my local copy of the `dev` branch I already tested a similar solution for this issue.
Just made the changes in ´main` branch.

**Comment by thorstenspille** [comment]
Fixed, already included in `main` branch

**Comment by thorstenspille** [comment]
If the proxmox host language differs from that one configured for the LXC container, the noninteractive setting of `locale` is incomplete and `apt` will produce warnings. By default the LXC container inherits partial language settings from the proxmox host.

**Comment by LAWA-IT-Service** [comment]
maybe adding the folling exports after locale-gen

`export LANG=$LXC_LOCALE`
`export LANGUAGE=$LXC_LOCALE`
`export LC_CTYPE=C `

**Comment by thorstenspille** [comment]
setting locales ist still a piece of crap...
priority=low!

**Comment by thorstenspille** [comment]
Added en_US.UTF-8 as secondary default language, this should prevent warnings in most cases.
