### ISSUE TITLE
lxc attributes like hostname are not set as in conf defined

### ISSUE THREAD

**Issue by matwun** [bashclub/zamba-lxc-toolbox#27]
The script install.sh should change the values for hostname, memroy, swap etc. in line 109, but doesn't.

Reason: ';' is missing at the end of lines 104 and 106

**Comment by thorstenspille** [comment]
Hi @matwun,
on our Proxmox servers the script is working correctly, so this behaviour seems to depend on your environment or your configuration.
Can you please post some information about your environment, like Proxmox version, (no) subscription, configured values in your zamba.conf?

**Comment by matwun** [comment]
Hallo Thorsten
Ich hab nochmals mehrere Test durchgeführt und nun den (meinen) Fehler gefunden. Wenn ich in zamba.conf in Zeile 73
LXC_TIMEZONE="Europe/Zuerich"
eintrage, funktioniert das Script für den Member Server zwar korrekt, übernimmt aber keine der Einstellungen (hostname, Memory etc.)
Mit der korrekten Timezone Europe/Zurich funktioniert alles bestens.
Vielen Dank für das Script, ich find's echt cool und Sorry für den Zusatzaufwand.
Gruss, Matthias
