### ISSUE TITLE
check devel toolbox

### ISSUE THREAD

**Issue by diddip21** [bashclub/zamba-lxc-toolbox#32]
- [ ] zmb-standalone => ZMB (Samba) standalone server with ZFS volume snapshot support (previous versions)
- [ ] zmb-ad => ZMB (Samba) Active Directory Domain Controller, DNS Backends SAMBA_INTERNAL and BIND9_DLZ are supported
- [ ] zmb-member => ZMB (Samba) AD member with ZFS volume snapshot support (previous versions)
- [x] mailpiler => mailpiler mail archive mailpiler.org
- [x] matrix => Matrix Synapse Homeserver matrix.org with Element Web Element on github
- [x] nextcloud => Nextcloud Server nextcloud.com with fail2ban und redis configuration
- [x] checkmk => CheckMK 2.0 Raw Edition checkmk.com with our Fork of Matrix Notification Plugin (https://github.com/bashclub/check_mk_matrix_notifications)
- [x] open3a => Open3A accounting software for small and medium business open3a.de
- [x] debian-unpriv => Debian unprivileged container with basic toolset
- [x] debian-priv => Debian privileged container with basic toolset

**Comment by diddip21** [comment]
- [x] checkmk
![image](https://user-images.githubusercontent.com/38922528/127909886-2223dbcc-079d-4381-99b3-5f66839bb5c3.png)
![image](https://user-images.githubusercontent.com/38922528/127909896-6c05e97c-3239-4108-bc36-f78c002de1b7.png)

**Comment by diddip21** [comment]
- [x] open3a
![image](https://user-images.githubusercontent.com/38922528/127911226-a18888b6-eeb7-429b-b0a9-e87c98878a38.png)

**Comment by thorstenspille** [comment]
Already Released, new Ticket for Bugfixing etc.
