### ISSUE TITLE
open3a wrong ipaddress [develtest]

### ISSUE THREAD

**Issue by diddip21** [bashclub/zamba-lxc-toolbox#33]
Finish Message
Your open3a installation is now complete. Please continue with setup in your Browser:
URL:            http://192.168.100.200/24
Login:          Admin
Password:       Admin

Mysql-Settings:
Server:         localhost
User:           open3a
Password:       KjFToTglK6XDeKkYqETB
Database:       open3a

Wrong IP-Addresse (used dhcp no static ip)

**Comment by thorstenspille** [comment]
priority=low!
