### ISSUE TITLE
possibility to deploy Secondary DC

### ISSUE THREAD

**Issue by rootgremlin** [bashclub/zamba-lxc-toolbox#52]
the current scripts only allow do deploy a 
Primary DC (like  https://wiki.samba.org/index.php/Setting_up_Samba_as_an_Active_Directory_Domain_Controller ) or an ordinary 
member Server. (like  https://wiki.samba.org/index.php/Setting_up_Samba_as_a_Domain_Member ) 

Please also include the possibility to deploy a 
secondary DC (like https://wiki.samba.org/index.php/Joining_a_Samba_DC_to_an_Existing_Active_Directory )

**Comment by thorstenspille** [comment]
Heres the secondary DC, will be in next release.
https://github.com/bashclub/zamba-lxc-toolbox/commit/65050ad33ed0f6e8c5cc712d0754ecbf941eb178
