### ISSUE TITLE
Add ecoDMS Container

### ISSUE THREAD

**Issue by ssoftS** [bashclub/zamba-lxc-toolbox#61]
https://www.ecodms.de/index.php/de/

**Comment by Silversurfer1961** [comment]
System requirements version 21.12
Privileged Debian 11 Container with Nesting=1
8 GB RAM
2 Cores
1GB HDD System + xGB Storage for data (32 GB should be good for starters)

```
apt update && apt dist-upgrade -y
apt install -y sudo mc
echo "deb http://www.ecodms.de/ecodms_211264/bullseye /" > /etc/apt/sources.list.d/ecodms.list
wget -O - http://www.ecodms.de/gpg/ecodms.key | sudo apt-key add -
apt update
apt install -y ecodmsserver
```

Choose Language
accept license

Download corresponding Client from https://www.ecodms.de/index.php/de/download/ecodms-archiv/ecodms-burns/ecodms-build-21-12
Have fun

**Comment by thorstenspille** [comment]
Ist drin https://www.youtube.com/watch?v=2Js-p7fK2x4
