### ISSUE TITLE
Fehler in Proxmox Backup-Server

### ISSUE THREAD

**Issue by md61267** [bashclub/zamba-lxc-toolbox#64]
beim Versuch einen PBS aufzusetzen mit dem Script:
bash install.sh -i3015 und der Auswahl 9
kommt folgende Fehlermeldung:

Fehl:4 http://download.proxmox.com/debian/pbs bullseye InRelease
  Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY DD4BA3917E23BF59
Paketlisten werden gelesen… Fertig
W: GPG-Fehler: http://download.proxmox.com/debian/pbs bullseye InRelease: Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY DD4BA3917E23BF59
E: Das Depot »http://download.proxmox.com/debian/pbs bullseye InRelease« ist nicht signiert.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
E: Paket proxmox-backup-server kann nicht gefunden werden.
/root/install-service.sh: Zeile 22: proxmox-backup-manager: Kommando nicht gefunden.

**Comment by thorstenspille** [comment]
Sieht eher nach fehlerhafter Netzwerkkonfiguration des LXC Containers aus. Mit funktionierender Internetverbindung (IP, Gateway und DNS) läuft auch die PBS Installation durch.

**Comment by thorstenspille** [comment]
https://github.com/bashclub/zamba-lxc-toolbox/blob/e78ee9e082c4c0b271497bbbeb4c16d0e3c7d4b2/src/proxmox-pbs/install-service.sh#L17
Der Download schlägt bei dir fehl, die Logs sind Folgefehler, wahrscheinlich wird es aber schon früher Fehler bei der Installation gegeben haben.

**Comment by DerFossiBaer** [comment]
Bitte ggf. Ticket erneut öffnen
