### ISSUE TITLE
Nextcloud https

### ISSUE THREAD

**Issue by cryd-s** [bashclub/zamba-lxc-toolbox#81]
Hi there,

i have installed the nextcloud but now i have big trouble to switch it to https.
Can someone tell me how to do this? Editing the config.php doesnt help. 

Why i want to do? 
Cause i have a non valid certificate in my network - this makes trouble with my internal dns rewrite (192.168.178.151 to cloud.xxxx.de)

**Comment by cryd-s** [comment]
![image](https://user-images.githubusercontent.com/47699362/223659380-4b034e28-cdc5-42a6-a391-2b57e3616528.png)

**Comment by cryd-s** [comment]
![image](https://user-images.githubusercontent.com/47699362/223659478-c92fb12e-a84c-4622-9011-1237c69a45f1.png)
![image](https://user-images.githubusercontent.com/47699362/223659611-58fffc2b-0825-40b4-894c-67f74cb6f7d2.png)

**Comment by DerFossiBaer** [comment]
The nextcloud container in the lxc toolbox is designed to work behind a proxy like nginx proxy or haproxy. 
If you want to install the nextcloud without proxy in front then the hole configuration for letsencrypt must be added.

**Comment by cryd-s** [comment]
Ok can u tell me how to do this?

**Comment by thorstenspille** [comment]
The most simple way to install a signed tls certificate is to install certbot or acme-sh onto the nextcloud container, generate a letsencrypt certificate and replace the certificate and key path in the nginx config file: `/etc/nginx/conf.d/nextcloud.conf` Line 155 - 156
~~~
- ssl_certificate /etc/ssl/certs/nextcloud.crt;
- ssl_certificate_key /etc/ssl/private/nextcloud.key;
+ ssl_certificate /etc/letsencrypt/live/cloud.yourdomain.tld/fullchain.pem;
+ ssl_certificate_key /etc/letsencrypt/live/cloud.yourdomain.tld/privkey.pem;
~~~

**Comment by cryd-s** [comment]
Ihr seids aus Deutschland wie ich in dem einen YT Video gesehen hab. Gibts vllt die Möglichkeit mir mal per Teams oder Discord auf die Sprünge zu helfen.
Bin recht neu in der ganzen Proxmox Welt und würde gern diese Nextcloud installieren und sauber bei mir hier betreiben.

Meine Voraussetzungen:

Normales Fritzbox Netzwerk
Adguard für DNS Umschreibung 
Proxmox

**Comment by thorstenspille** [comment]
@cryd-s du hast eine PN bei Discord.
