### ISSUE TITLE
bookstack minimum php version

### ISSUE THREAD

**Issue by JanMali** [bashclub/zamba-lxc-toolbox#82]
Since Bookstack v23.01, the minimum supported PHP version has changed from 7.4 to 8.0.2 ([Release Notes](https://www.bookstackapp.com/blog/bookstack-release-v23-02/)). At today, the toolbox installs php-fpm 7.4.33, which let the installation fails.

**Comment by thorstenspille** [comment]
Im dev branch migriert auf Debian bookworm.
