### ISSUE TITLE
Minor bug in install.sh in case of LXC_AUTOTAG=0

### ISSUE THREAD

**Issue by duraslexan** [bashclub/zamba-lxc-toolbox#83]
Hi, I detected a minor bug in install.sh in case the variable LXC_AUTOTAG is set to 0 in zamba.conf. In the relevant code part an else statement with TAGS="" is missing or as alternative a default set statement could do the same. I can provide an commit but I think the change is so minor, that anybody from the active constributers should do it.

By the way this is a very helpful tool.

**Comment by thorstenspille** [comment]
fixed in dev branch
