### ISSUE TITLE
X-Robots-Tag von "none" to "noindex, nofollow"

### ISSUE THREAD

**Issue by Liixee** [bashclub/zamba-lxc-toolbox#84]
Seit Version 26 von Nextcloud kommt die Fehlermeldung:

[„X-Robots-Tag“-HTTP-Header ist nicht so konfiguriert, dass er „noindex, nofollow“ entspricht](https://help.nextcloud.com/t/nextcloud-hub-4-26-0-0-x-robots-tag-http-header-ist-nicht-so-konfiguriert-dass-er-noindex-nofollow-entspricht/158289)

Daher bitte in der Konfig die Zeile
add_header X-Robots-Tag                         "none"          always;

In
add_header X-Robots-Tag                         "noindex, nofollow" always;

ändern.

Viele Grüße Lixe

**Comment by thorstenspille** [comment]
Ist gefixt, liegt im main.
