### ISSUE TITLE
zmb-ad-join

### ISSUE THREAD

**Issue by araschk** [bashclub/zamba-lxc-toolbox#92]
Hallo, ich versuche gerade ein zmb-ad-join in eine Server 2012r2 / 2022 Domäne. Der 2012er Server soll abgelöst werden.
Zum einen hab ich heraus gefunden das in der zamba.conf der Domänen ZMB_REALM und ZMB_Domain komplett groß geschrieben werden muss, sonst schlägt der kinit fehlt. Ein Hinweis in der conf in den Kommentaren wäre hilfreich. ;-)
Des weiteren hab ich heraus gefunden das das Domänen Schema Level durch den AD Join des 2022 Servers auf Version 88 steht, samba aber aktuell wohl nur bis Level 69 (2012R2) Supportet. Im Samba Bugzilla hab ich diesen Artikel gefunden:
https://bugzilla.samba.org/show_bug.cgi?id=13619#c5
https://gitlab.com/samba-team/samba/-/merge_requests/3080
so das wohl mit einer neueren Version von Samba ein Join in eine 2016er Domäne möglich sein soll, der Change ist aber wohl noch nicht komplett abgeschlossen. Ich hoffe das dann auch ein Join in eine 2022er Domäne möglich wird. Der FL Unterschied ist nicht mehr wirklich groß, Version 87 auf 88.
https://wiki.samba.org/index.php/AD_Schema_Version_Support
Wäre schön wenn ihr die Skripte dahingehend erweitern könntet. Ich verfolge den Channel seit einiger Zeit, schaffe es leider nicht immer pünktlich zum Live Stream.
Gruß
Andreas

**Comment by araschk** [comment]
Ich hab demnächst nochmal die Möglichkeit eine ad-join in eine reine 2012R2 Domäne zu probieren, da steht auch die Ablösung an.

**Comment by thorstenspille** [comment]
Hi Andreas,

wir haben bereits im dev Branch die Container auf Debian bookworm umgestellt, jedoch noch nicht ausgiebig getestet. Die Samba Version ist dort relativ aktuell (4.17.9 - http://packages.debian.org/bookworm/samba).

Gruß
Thorsten

**Comment by thorstenspille** [comment]
Hi Andreas,
in der letzten Woche hatte ich einen AD Workshop zu dieser Lösung gemacht. dort habe ich auch eine Migration vom W22 gezeigt. Den FunctionLevel für Domain und Forest musste ich via PowerShell auf Windows2008R2 herunterstufen, damit es funktioniert hat.
Die dev Toolbox ist auf höchstmöglichem Versionsstand (bookworm-backports), damit sollte es keine Probleme mit modernen Systemen geben.
Release wird in kürze da sein.
