### ISSUE TITLE
Bookstack PHP Version

### ISSUE THREAD

**Issue by araschk** [bashclub/zamba-lxc-toolbox#93]
Moin,
jetzt wollte ich Bookstack ausprobieren und bekomme einen PHP Versions Fehler:

Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Script Illuminate\Foundation\ComposerScripts::postAutoloadDump handling the post-autoload-dump event terminated with an exception

In platform_check.php line 24:
  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2". You are running 7.4.33.

Hab versucht die src/bookstack/install-service.sh anzupassen, hat aber so nicht funktioniert. Könnt ihr da vielleicht mal einen Blick drauf werfen. THX
Nordische Grüße
Andreas Raschke

**Comment by thorstenspille** [comment]
Hi Andreas,

hier ist ebenfalls im dev Branch eine auf Debian bookworm umgestellte Version mit aktuellen Paketen.

Gruß
Thorsten
