### ISSUE TITLE
move existing NC installation into your LXC

### ISSUE THREAD

**Issue by Surfer2010** [bashclub/zamba-lxc-toolbox#94]
Hello,

great great tool really, I was wondering how I would move my existing NC Installation (Docker) to your LXC?

Thanks fot the help/advice

**Comment by thorstenspille** [comment]
Hello,
it's well documented by Nextcloud:
### Backup
https://docs.nextcloud.com/server/latest/admin_manual/maintenance/backup.html
### Restore
https://docs.nextcloud.com/server/latest/admin_manual/maintenance/restore.html
