### ISSUE TITLE
ansible-semaphore 

### ISSUE THREAD

**Issue by rowie** [bashclub/zamba-lxc-toolbox#98]
++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*++*
Created symlink /etc/systemd/system/multi-user.target.wants/semaphore.service → /etc/systemd/system/semaphore.service.

######################################################################

    Please note this user and password for the semaphore login:
        '' / ''
                Enjoy your semaphore intallation.

######################################################################

**Comment by thorstenspille** [comment]
Hast du eine neue config-Datei aus der zamba.conf.example erzeugt?
Die Datei hab ich im letzten Update geändert und enthält die Variablen für den ansible-semaphore User.

**Comment by rowie** [comment]
JA, hab ich am Abend wie wir gesprochen haben gemacht. Ich benenn den Ordner immer um und zieh neu. VersionsTag in der config wär nice to have. Geht das?

**Comment by rowie** [comment]
Er legt jedenfalls keinen User an!

**Comment by thorstenspille** [comment]
Das random password in der config Datei mag install.sh nicht, müsste sogar abbrechen mit aktueller config.

Bei mir klappt das user adden mit statischem Passwort.

In der zmb.conf müssen folgende 4 Zeilen unten drin stehen:
~~~
SEMAPHORE_ADMIN=admin
SEMAPHORE_ADMIN_DISPLAY_NAME="Semaphore Administrator"
SEMAPHORE_ADMIN_EMAIL="admin@zmb.rocks"
SEMAPHORE_ADMIN_PASSWORD="Start123"
~~~
Das klappt nur, wenn du eine neue config-Datei aus der zamba.conf.example erzeugst oder die Zeilen menuell hinzufügst.
