### ISSUE TITLE
/etc/hosts hostname nuke (Zammad)

### ISSUE THREAD

**Issue by MrGeneration** [bashclub/zamba-lxc-toolbox#99]
I stumbled upon this part of the Zammad installation of this repo:
https://github.com/bashclub/zamba-lxc-toolbox/blob/main/src/zammad/install-service.sh#L22-L32

That makes me wonder: What issue / problem was tried to be solved there?

**Comment by thorstenspille** [comment]
Removed it and webserver config is now based on the contrib...zammad_ssl.conf.
Currently in dev, will soon be released.
